as_token: 2ed773ab-9eb8-41d3-8c9a-77f864dd8086
hs_token: 9276c728-5f84-4fcc-86d9-3805d8cefc9a
id: slack-puppet
namespaces:
  users:
    - exclusive: true
      regex: '@_slackpuppet_.*'
  rooms: []
  aliases:
    - exclusive: true
      regex: '#_slackpuppet_.*'
protocols: []
rate_limited: false
sender_localpart: _slackpuppet_bot
url: 'http://mx-puppet-slack-srv:8432'
de.sorunome.msc2409.push_ephemeral: true
