---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pv-claim
  namespace: matrix-acc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

