apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/commonground/developer.overheid.nl/api
    context: .
    docker:
      dockerfile: api/Dockerfile
  - image: registry.gitlab.com/commonground/developer.overheid.nl/ui
    context: .
    docker:
      dockerfile: ui/Dockerfile
  tagPolicy:
    sha256: {}
  local:
    push: false
profiles:
- name: minikube
  deploy:
    helm:
      releases:
      - name: don
        chartPath: helm/don
        valuesFiles:
        - helm/don/values-dev.yaml
        values:
          apiImage: registry.gitlab.com/commonground/developer.overheid.nl/api
          uiImage: registry.gitlab.com/commonground/developer.overheid.nl/ui
        namespace: don-dev
- name: release
  build:
    tagPolicy:
      gitCommit: {}
    local:
      push: true
- name: deploy-review-app
  deploy:
    helm:
      releases:
        - name: don-review-app
          chartPath: helm/don
          valuesFiles:
            - helm/don/values-review-app.yaml
          values:
            apiImage: registry.gitlab.com/commonground/developer.overheid.nl/api
            uiImage: registry.gitlab.com/commonground/developer.overheid.nl/ui
          namespace: don-review-app
          setValueTemplates:
            domain: '{{.DOMAIN}}'
- name: deploy-prod
  deploy:
    helm:
      releases:
      - name: don-prod
        chartPath: helm/don
        valuesFiles:
        - helm/don/values-prod.yaml
        values:
          apiImage: registry.gitlab.com/commonground/developer.overheid.nl/api
          uiImage: registry.gitlab.com/commonground/developer.overheid.nl/ui
        namespace: don-prod
