{{ with set . "component" "api" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {{ include "don.common.metadata" . | nindent 2 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "don.common.metadata-labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "don.common.metadata-labels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: {{.Values.apiImage}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: GITLAB_URL
              valueFrom:
                secretKeyRef:
                  name: gitlab
                  key: url
            - name: GITLAB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab
                  key: access_token
            - name: GITLAB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: gitlab
                  key: project_id
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata: {{ include "don.common.metadata" . | nindent 2 }}
spec:
  selector: {{ include "don.common.metadata-labels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
{{ end }}