{{ with set . "component" "api" }}
apiVersion: apps/v1
kind: Deployment
metadata: {{ include "don.common.metadata" . | nindent 2 }}
spec:
  replicas: {{.Values.replicas}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: {{ include "don.common.metadata-labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "don.common.metadata-labels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: {{.Values.apiImage | quote}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: {{.component}}
            - secretRef:
                name: gitlab-creds
          env:
            - name: ALLOWED_HOST
              value: "{{.Values.domain}}"
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: "{{ .Values.postgresDb }}"
            - name: LINKCHECKER_ENABLED_DEFAULT
              value: "{{.Values.linkcheckerEnabledDefault}}"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata: {{ include "don.common.metadata" . | nindent 2 }}
spec:
  selector: {{ include "don.common.metadata-labels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 8000
---
apiVersion: v1
kind: Secret
metadata: {{ include "don.common.metadata" . | nindent 2 }}
type: Opaque
data:
  SECRET_KEY: {{.Values.secretKey | b64enc | quote}}
{{ end }}
