{{ with set . "component" "load-superuser" }}
{{ if .Values.loadTestData }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .component }}-{{ randAlphaNum 5 | lower }}"
  labels: {{ include "don.common.metadata-labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: {{ .component }}
          image: {{.Values.apiImage | quote}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          command: [
            "python",
            "manage.py",
            "load_superuser",
            "--username",
            {{.Values.testAdminUsername}},
            "--email",
            {{.Values.testAdminEmail}}
          ]
          envFrom:
            - secretRef:
                name: api
            - secretRef:
                name: {{.component}}
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: "{{ .Values.postgresDb }}"
      restartPolicy: Never
---
apiVersion: v1
kind: Secret
metadata: {{ include "don.common.metadata" . | nindent 2 }}
type: Opaque
data:
  DJANGO_SUPERUSER_PASSWORD: {{.Values.testAdminPassword | b64enc | quote}}
{{ end }}
{{ end }}
