{{ with set . "component" "migrate-and-fill-db" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .component }}-{{ randAlphaNum 5 | lower }}"
  labels: {{ include "don.common.metadata-labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: {{ .component }}
          image: {{.Values.apiImage | quote}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
{{ if .Values.loadDatabaseFixtures }}
          command: ["/srv/don-api/bin/migrate-and-fill", "--fixtures-path", "../fixtures.sql"]
{{ else }}
          command: ["/srv/don-api/bin/migrate-and-fill"]
{{ end }}
          envFrom:
          - secretRef:
              name: postgres-auth
          env:
            - name: POSTGRES_DSN
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres/{{ .Values.postgresDb }}?sslmode=disable
      restartPolicy: Never
{{ end }}
