{{- if and .Values.loadTestData -}}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: don-cluster
  namespace: {{ .Release.Namespace }}
spec:
  teamId: "don"
  volume:
    size: 5Gi
  numberOfInstances: 2
  users:
    don:  # database owner
    - superuser
    - createdb
  databases:
    don: don  # dbname: owner
  postgresql:
    version: "11"
{{ end }}
