{{ with set . "component" "ui" }}
apiVersion: apps/v1
kind: Deployment
metadata: {{ include "don.common.metadata" . | nindent 2 }}
spec:
  replicas: {{.Values.replicas}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: {{ include "don.common.metadata-labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "don.common.metadata-labels" . | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: {{.Values.uiImage | quote}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata: {{ include "don.common.metadata" . | nindent 2 }}
spec:
  selector: {{ include "don.common.metadata-labels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: {{ include "don.common.metadata" . | nindent 2 }}
  annotations:
    # Traefik is the default ingress provider in our setup
    ingress.kubernetes.io/frame-deny: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/referrer-policy: "same-origin"
    ingress.kubernetes.io/content-security-policy: "default-src 'self'; connect-src https:; img-src 'self' data:; style-src 'self' 'unsafe-inline'; object-src 'none'; worker-src 'self' blob:; child-src 'self' blob:;"
    ingress.kubernetes.io/hsts-max-age: "315360000"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "server: hide";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Xss-Protection: 1";
      more_set_headers "Referrer-Policy: no-referrer";
      more_set_headers "Permissions-Policy: geolocation=(), microphone=()";
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: ingress-tls
      hosts:
        - {{.Values.domain}}
  rules:
    - host: {{.Values.domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  name: http
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  name: http
{{ end }}
