imagePullPolicy: Always
ingressClass: nginx

domain: don.minikube

apiImage: registry.gitlab.com/commonground/developer.overheid.nl/api:master
uiImage: registry.gitlab.com/commonground/developer.overheid.nl/ui:master
docsImage: registry.gitlab.com/commonground/developer.overheid.nl/docs:master

gitlabUrl: https://gitlab.com
gitlabAccessToken: secret
gitlabProjectId: "0"

postgresUser: don
postgresPassword: don
postgresDb: don
postgresDsn: postgres://don:don@postgres/don?sslmode=disable
postgresPvcName: postgres-data-volume
loadDatabaseFixtures: false

storageType: Durable

replicas: 3
