# Generated by Django 3.0.5 on 2020-11-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_api_links_noconstraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIDesignRuleTestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_rule_test_suite', models.UUIDField(null=True)),
                ('api', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.API', to_field='api_id')),
            ],
        ),
    ]
