# Generated by Django 3.0.5 on 2020-11-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidesignruletestsuite',
            old_name='design_rule_test_suite',
            new_name='uuid',
        ),
    ]
