# Generated by Django 3.0.5 on 2020-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0002_auto_20201111_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRulesConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='67d6c7b4ad656916bee7a2141a1414738515687f', max_length=255)),
                ('default_version', models.IntegerField(default=1, help_text='This is the version that will be tested.')),
            ],
            options={
                'verbose_name': 'Design rules Configuration',
            },
        ),
    ]
