# Generated by Django 3.0.5 on 2020-11-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_api_links_noconstraint'),
        ('design_rules', '0003_designrulesconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidesignruletestsuite',
            name='api',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Environment'),
        ),
    ]
