# Generated by Django 3.0.5 on 2020-11-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0004_auto_20201113_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidesignruletestsuite',
            old_name='api',
            new_name='environment',
        ),
    ]
