# Generated by Django 3.0.5 on 2020-11-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0005_auto_20201113_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrulesconfiguration',
            name='base_url',
            field=models.CharField(default='https://staging.api-test.nl/', help_text='The base url of the called environment', max_length=255),
        ),
    ]
