# Generated by Django 3.0.5 on 2020-11-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0006_designrulesconfiguration_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrulesconfiguration',
            name='base_url',
            field=models.CharField(default='https://staging.api-test.nl/', help_text='The base url of the called environment, make sure that it ands with a slash', max_length=255),
        ),
    ]
