# Generated by Django 3.0.5 on 2020-11-25 11:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_api_links_noconstraint'),
        ('design_rules', '0007_auto_20201120_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidesignruletestsuite',
            name='environment',
        ),
        migrations.AddField(
            model_name='apidesignruletestsuite',
            name='api',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.API'),
        ),
        migrations.CreateModel(
            name='DesignRuleSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('percentage_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('test_version', models.CharField(default='', max_length=200)),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='design_rules.APIDesignRuleTestSuite')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='DesignRuleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type_url', models.URLField()),
                ('rule_type_name', models.CharField(default='', max_length=250)),
                ('rule_type_description', models.TextField(default='')),
                ('success', models.BooleanField(blank=True, default=False)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None)),
                ('design_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='design_rules.DesignRuleSession')),
            ],
        ),
    ]
