# Generated by Django 3.0.5 on 2020-11-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_rules', '0008_auto_20201125_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designruleresult',
            old_name='design_rule',
            new_name='session',
        ),
    ]
