# Generated by Django 3.0.5 on 2020-11-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_api_links_noconstraint'),
        ('design_rules', '0009_auto_20201125_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidesignruletestsuite',
            name='api',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_suite', to='core.API', to_field='api_id'),
        ),
    ]
