Deploy production:
  stage: deploy
  image: registry.gitlab.com/commonground/core/review-app-deployer:latest
  script:
    - |
      helm upgrade --install don-prod ./helm/don \
      --namespace don-prod \
      --set "secretKey=$SECRET_KEY" \
      --set-string "gitlabProjectId=$GITLAB_PROJECT_ID" \
      --set "gitlabUrl=$GITLAB_URL" \
      --set "gitlabAccessToken=$GITLAB_ACCESS_TOKEN" \
      --set "apiTestBaseUrl=$API_TEST_BASE_URL" \
      --set "apiTestToken=$API_TEST_TOKEN" \
      --set "apiImage=$IMAGE_PREFIX/api:$CI_COMMIT_SHORT_SHA" \
      --set "uiImage=$IMAGE_PREFIX/ui:$CI_COMMIT_SHORT_SHA" \
      --set "docsImage=$IMAGE_PREFIX/docs:$CI_COMMIT_SHORT_SHA" \
      --set "dbTerminationPolicy=DoNotTerminate" \
      --set "linkcheckerImage=$IMAGE_PREFIX/linkchecker:$CI_COMMIT_SHORT_SHA" \
      --set "linkcheckerEnabledDefault=true" \
      --set "domain=$DOMAIN"
  environment:
    name: prod
    url: https://$DOMAIN
  tags:
  - cg
  - docker
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_PATH == "commonground/don/developer.overheid.nl"'
