#!/bin/sh
set -eu
MIGRATE=0
case "$*" in
"-h" | "--help")
    echo "Dump sql to create the schema for the core module."
    echo "Make sure you have your python virtual environment activated (if applicable)."
    echo "To update the schema file, run 'generate_test_sql.sh > testschema.sql'."
    echo
    echo "To generate an *accurate* sql dump, this script also needs to apply the"
    echo "migrations one by one, starting from an empty database. Add the"
    echo "--apply-migrations flag to do so. Or alternatively, push your branch without"
    echo "the updated testschema.sql and let the CI pipeline generate it as an artifact"
    echo "for you. (Then download it and add it to your branch.)"
    exit
    ;;
"--apply-migrations")
    MIGRATE=1
    ;;
esac

cd "$(dirname "$0")"

echo "-- Autogenerated DDL for django module 'core'. Do not edit!"
echo "-- Regenerate using 'generate_test_sql.sh > testschema.sql'"
echo "--"
for m in `ls ../../api/core/migrations | grep -v __ | cut -f1 -d.`
do
    python ../../api/manage.py sqlmigrate core $m
    if [ "$MIGRATE" = 1 ]
    then
        python ../../api/manage.py migrate core $m >&2
    fi
done
