# Generated by Django 3.0.5 on 2020-05-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(choices=[('production', 'Productie'), ('acceptance', 'Acceptatie'), ('demo', 'Demo')], max_length=31),
        ),
    ]
