# Generated by Django 3.0.5 on 2020-05-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_authentication',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('none', 'None'), ('mutual_tls', 'Mutual Tls'), ('api_key', 'Api Key'), ('ip_whitelist', 'Ip Whitelist')], default='unknown', max_length=31),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('rest_json', 'Rest Json'), ('rest_xml', 'Rest Xml'), ('soap_xml', 'Soap Xml'), ('grpc', 'Grpc'), ('graphql', 'Graphql'), ('sparql', 'Sparql'), ('wfs', 'Wfs'), ('wms', 'Wms')], default='unknown', max_length=31),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(choices=[('production', 'Production'), ('acceptance', 'Acceptance'), ('demo', 'Demo')], max_length=31),
        ),
    ]
