# Generated by Django 3.0.5 on 2020-06-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_enum_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='documentation_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
