# Generated by Django 3.0.5 on 2020-06-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doc_url_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='contact_chat',
        ),
        migrations.RemoveField(
            model_name='api',
            name='contact_fax',
        ),
    ]
