# Generated by Django 3.0.5 on 2020-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_fax_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='terms_support_response_time',
            field=models.PositiveIntegerField(help_text='Measured in number of workdays', null=True),
        ),
    ]
