# Generated by Django 3.0.5 on 2020-08-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_response_time_workdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('location', models.TextField(max_length=255)),
                ('registration_url', models.URLField(max_length=2000)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
