# Generated by Django 3.0.5 on 2020-08-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLProbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.SmallIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.URL')),
            ],
        ),
        migrations.AddIndex(
            model_name='urlprobe',
            index=models.Index(fields=['url', '-timestamp'], name='core_urlpro_url_id_82a002_idx'),
        ),
    ]
