# Generated by Django 3.0.5 on 2020-08-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_url_urlprobe_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLApiLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('forum', 'Forum'), ('contact', 'Contact'), ('production_api', 'Production Api'), ('production_spec', 'Production Spec'), ('production_doc', 'Production Doc'), ('acceptance_api', 'Acceptance Api'), ('acceptance_spec', 'Acceptance Spec'), ('acceptance_doc', 'Acceptance Doc'), ('demo_api', 'Demo Api'), ('demo_spec', 'Demo Spec'), ('demo_doc', 'Demo Doc')], max_length=31)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_links', to='core.API')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_links', to='core.URL')),
            ],
        ),
    ]
