# Generated by Django 3.0.5 on 2020-11-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_code_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='source',
            field=models.CharField(choices=[('GitLab repository', 'Gitlab'), ('GitHub repository', 'Github'), ('GitLab snippet', 'Gitlab Snippet'), ('GitHub gist', 'Github Gist')], max_length=31),
        ),
    ]
