# Generated by Django 3.0.5 on 2020-11-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_code_sharing_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeapi',
            name='api',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.API', to_field='api_id'),
        ),
        migrations.AlterField(
            model_name='urlapilink',
            name='api',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='url_links', to='core.API'),
        ),
    ]
