# Generated by Django 3.0.5 on 2021-02-16 15:32
""" Fix for old db artefacts """

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_apidesignruletestsuite_designruleresult_designrulesession'),
    ]

    operations = [
        migrations.RunSQL("""
            DELETE FROM core_urlapilink
            WHERE api_id NOT IN (SELECT id FROM core_api)""")
    ]
