# Generated by Django 3.0.5 on 2020-11-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_api_links_noconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apibadge',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.API', to_field='api_id'),
        ),
        migrations.AlterField(
            model_name='codeapi',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.API', to_field='api_id'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations_to', to='core.API', to_field='api_id'),
        ),
        migrations.AlterField(
            model_name='urlapilink',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_links', to='core.API'),
        ),
    ]
