# Generated by Django 3.0.5 on 2021-02-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_api_links_fix_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidesignruletestsuite',
            name='api',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='test_suite', to='core.API', to_field='api_id'),
        ),
    ]
