# Generated by Django 3.0.5 on 2021-02-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210209_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidesignruletestsuite',
            name='api',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='test_suite', to='core.API', to_field='api_id'),
        ),
    ]
