# Generated by Django 3.1.7 on 2021-02-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_dbconstraint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='urlprobe',
            name='core_urlpro_url_id_82a002_idx',
        ),
        migrations.AlterField(
            model_name='apidesignruletestsuite',
            name='api',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_suite', to='core.api', to_field='api_id'),
        ),
    ]
