# Generated by Django 3.1.7 on 2021-03-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_make_testsuite_cascading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('oin', models.CharField(help_text='Organization Identification Number', max_length=20, unique=True, verbose_name='oin')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'organization',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organization'),
        ),
    ]
