# Generated by Django 3.1.7 on 2021-03-11 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeapi',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.api', to_field='api_id'),
        ),
    ]
