# Generated by Django 3.1.7 on 2021-03-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_create_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='organization_name',
        ),
    ]
