# Generated by Django 3.1.7 on 2021-03-11 13:30

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_api_organization_name'),
    ]

    operations = [
        TrigramExtension(),
    ]
