# Generated by Django 3.1.7 on 2021-03-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_trigram_extension'),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE INDEX core_api_search_idx ON core_api USING GIN (
                    UPPER(description) gin_trgm_ops, UPPER(service_name) gin_trgm_ops);
                CREATE INDEX core_org_search_idx ON core_organization USING GIN (
                    UPPER(name) gin_trgm_ops);
            """,
            """
                DROP INDEX core_api_search_idx;
                DROP INDEX core_org_search_idx;
            """
        ),
    ]
