# Generated by Django 3.1.7 on 2021-03-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_search_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'verbose_name': 'API', 'verbose_name_plural': 'APIs'},
        ),
        migrations.AlterField(
            model_name='api',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='organization'),
        ),
    ]
